configs:
  secret:
    argocdServerAdminPassword: "$2a$10$9fmHquh/JsJXXxBHoRb/ruPTqWTcKRSBL8GiTTQSspG/psQwhhcp2"
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
  cm:
    application.resourceTrackingMethod: annotation
server:
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - gitops.54.157.233.202.nip.io
